#-------------#-------------#-------------#-------------#-------------#-------------#-------------#-------------
#-------------------------------------------------CUSTOMERS----------------------------------------------------#
#--------------#-------------#-------------#-------------#-------------#-------------#-------------#------------

### Get all customers
GET http://localhost:8080/login

### Get a single customer by id
GET http://localhost:8080/customers/648cc8a8c502fca77c14fd02

### Create customer with the data of the body of the request
POST http://localhost:8080/customers HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "customer_name": "Antonio Martinez",
    "email": "tonihmartinez@gmail.com",
    "password": "Z@nchopanz4",
    "address": "456 Exeter Street, Cityville",
    "phone": "999-888-0011"
}

### Update customer with id
PUT http://localhost:8080/customers/048cc8a8c502fca77c14fd02 HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "customer_name": "Marcos Martinez",
    "email": "marcomartine@gmail.com",
    "password": "D@shjhj?", 
    "address": "456 Exeter Street, Cityville",
    "phone": "999-888-0011"
}

### Delete customer with id
DELETE  http://localhost:8080/customers/648f969fd5b23b1bb2a69f07

#-------------#-------------#-------------#-------------#-------------#-------------#-------------#-------------
#-------------------------------------------------PIZZAS-------------------------------------------------------#
#--------------#-------------#-------------#-------------#-------------#-------------#-------------#------------

### Get all pizzas
GET http://localhost:8080/pizzas

### Get a single pizza by id
GET http://localhost:8080/pizzas/6484b1527e439aee595cb80f

### Create pizza with the data of the body of the request
POST http://localhost:8080/pizzas HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "pizza_name": "Pepperoni and Jalapeno",
    "description": "Classic American pizza with tomato sauce, mozzarella cheese, pepperoni, and jalapeno.",
    "toppings": [
      "Tomato Sauce"
    ],
    "price": 10.99
}

### Update pizza with id
PUT http://localhost:8080/pizzas/648ed24bd33d3fc64e057933 HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "pizza_name": "Pepperoni and Jalapeno",
    "description": "Classic American pizza with tomato sauce, mozzarella cheese, pepperoni, and jalapeno.",
    "toppings": [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Pepperoni",
      "Jalapeno"
    ],
    "price": 10.99
}

### Delete pizza with id
DELETE  http://localhost:8080/pizzas/6484eb907cea11435b5e0f63



//########//########//########//########//########//########//########//########//########//
//########//########//########//########//########//########//########//########//########//

// PRODUCTION Deploy

### Get all customers
GET https://toni-pizzeria.onrender.com/customers

### Get a single customer by id
GET https://toni-pizzeria.onrender.com/customers/64682123955a52616a3e61ca

### Create customer with the data of the body of the request
POST https://toni-pizzeria.onrender.com/customers HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "firstName": "Marco",
    "lastName": "Martinez",
    "email": "marcomartine@gmail.com",
    "favoriteColor": "blue",
    "birthday": "01/05/68"
}

### Update customer with id
PUT https://toni-pizzeria.onrender.com/customers/64682123955a52616a3e61ca HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "firstName": "Vianney",
    "lastName": "Alcala",
    "email": "vianneyalcala@gmail.com",
    "favoriteColor": "indigo",
    "birthday": "06/15/94"
}

### Delete customer with id
DELETE  https://toni-pizzeria.onrender.com/customers/648b949ccbcf2305f93f4686

#-------------#-------------#-------------#-------------#-------------#-------------#-------------#-------------
#-------------------------------------------------PIZZAS-------------------------------------------------------#
#--------------#-------------#-------------#-------------#-------------#-------------#-------------#------------

### Get all pizzas
GET https://toni-pizzeria.onrender.com/pizzas

### Get a single pizza by id
GET https://toni-pizzeria.onrender.com/pizzas/6484b1527e439aee595cb80f

### Create pizza with the data of the body of the request
POST https://toni-pizzeria.onrender.com/pizzas HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "pizza_name": "Margherita",
    "description": "Classic Italian pizza with tomato sauce, mozzarella cheese, and fresh basil.",
    "toppings": [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Fresh Basil",
      "Aioli"
    ],
    "price": 10.99
}

### Update pizza with id
PUT https://toni-pizzeria.onrender.com/pizzas/64682123955a52616a3e61ca HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "pizza_name": "Pepperoni and Jalapeno",
    "description": "Classic American pizza with tomato sauce, mozzarella cheese, pepperoni, and jalapeno.",
    "toppings": [
      "Tomato Sauce",
      "Mozzarella Cheese",
      "Pepperoni",
      "Jalapeno"
    ],
    "price": 10.99
}

### Delete pizza with id
DELETE  https://toni-pizzeria.onrender.com/pizzas/6468ff25b4de866bdde4665e